#!/bin/bash
###
# This script modifies the autocompleteParser.js file to be compatible with worklets.
# autocompleteParser.js is generated by PeggyJS and uses some parts of syntax not supported by worklets.
# This script runs each time the parser is generated by the `generate-autocomplete-parser` command.
#
# It does two things:
#   1. Prepends the top-level 'worklet' directive so the parser runs on the UI thread.
#   2. Rewrites Peggy's `peg$SyntaxError` so it stays a plain constructor *function* that
#      assigns the error fields directly to `this`. The generated form relies on
#      `Error.call(this, ...)`, `Object.setPrototypeOf`, and `peg$subclass(peg$SyntaxError, Error)`,
#      none of which are worklet-safe. We must NOT turn it into an ES `class`: a class is the one
#      function form that cannot be invoked without `new`, and when the web bundle is transpiled for
#      older Safari the class is lowered with Babel's `_classCallCheck` guard, which throws
#      "Cannot call a class as a function" on /search (Sentry APP-CN8). A plain constructor function
#      avoids that guard entirely while remaining worklet-compatible.
###

filePath=$1

if [ ! -f "$filePath" ]; then
    echo "$filePath does not exist."
    exit 1
fi

# shellcheck disable=SC2016
# Prepend the 'worklet' directive, then replace the generated peg$SyntaxError constructor body
# (Error.call / Object.setPrototypeOf) with a plain self-assigning constructor function, and drop
# the worklet-incompatible peg$subclass(peg$SyntaxError, Error); call.
if awk '
    BEGIN {
        print "\47worklet\47"
        print ""
    }
    /^function peg\$SyntaxError\(/ {
        print "function peg$SyntaxError(message, expected, found, location) {"
        print "  this.message = message;"
        print "  this.expected = expected;"
        print "  this.found = found;"
        print "  this.location = location;"
        print "  this.name = \"SyntaxError\";"
        print "}"
        skip = 1
        next
    }
    skip && /^}/ { skip = 0; next }
    skip { next }
    { print }
' "$filePath" | sed 's/peg$subclass(peg$SyntaxError, Error);//g' > tmp.txt; then
    mv tmp.txt "$filePath"
    echo "Successfully updated $filePath"
else
    echo "An error occurred while modifying the file."
    rm -f tmp.txt
    exit 1
fi
